# Generated by Django 4.2.3 on 2023-07-06 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdventureTime', '0003_categoryplace_alter_comment_user_alter_rating_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoryplace',
            name='category',
        ),
        migrations.RemoveField(
            model_name='categoryplace',
            name='place',
        ),
        migrations.AddField(
            model_name='place',
            name='category',
            field=models.CharField(choices=[('business', 'business'), ('nature', 'nature'), ('party time', 'party time'), ('religion', 'religion'), ('adventure', 'adventure')], max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='CategoryPlace',
        ),
    ]
