# Generated by Django 4.2.3 on 2023-07-06 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdventureTime', '0004_remove_categoryplace_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6)]),
        ),
    ]
